
DROP TABLE TB_PESSOA CASCADE;
DROP TABLE TB_TIPO_CLIENTE;
DROP TABLE TB_GENDER;
DROP TABLE TB_ENDERECO;

CREATE TABLE TB_PESSOA (
    ID_PESSOA NUMBER(20),
    NOME VARCHAR2(100),
    DT_NASC DATE,
    EMAIL VARCHAR2(100),
    CPF_CNPJ VARCHAR(100),
    ID_TIPO_CLIENTE NUMBER(20),
    ID_GENDER NUMBER(20),
    ID_ENDERECO NUMBER(20)
)

ALTER TABLE TB_PESSOA
ADD CONSTRAINT pk_tb_pessoa PRIMARY KEY (ID_PESSOA);

CREATE TABLE TB_TIPO_CLIENTE(
    ID_TIPO_CLIENTE NUMBER(20),
    DESCRICAO VARCHAR2(100)
)

CREATE TABLE TB_GENDER(
    ID_GENDER NUMBER(20),
    GENDER VARCHAR2(100)
)

CREATE TABLE TB_ENDERECO(
    ID_ENDERECO NUMBER(20),
    LOGRADOURO VARCHAR2(100),
    NUMERO NUMBER(10),
    COMPLEMENTO VARCHAR2(100),
    NOME_ENDERECO VARCHAR(100)
)